// <auto-generated />
using System;
using KindergartenManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KindergartenManagementSystem.Migrations
{
    [DbContext(typeof(KindergartenMSContext))]
    [Migration("20210907160006_enter")]
    partial class enter
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KindergartenManagementSystem.Models.EnterModels.Enter_Request", b =>
                {
                    b.Property<int>("Pro_id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Approver");

                    b.Property<DateTime>("Birthday");

                    b.Property<int>("Child_Id");

                    b.Property<string>("Cla")
                        .IsRequired();

                    b.Property<string>("Gua_name")
                        .IsRequired();

                    b.Property<string>("Gua_phone")
                        .IsRequired();

                    b.Property<string>("Home_addr")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<bool>("Sex");

                    b.Property<string>("Starter");

                    b.Property<int>("Status");

                    b.Property<string>("Suggest");

                    b.HasKey("Pro_id");

                    b.ToTable("enter_Requests");
                });

            modelBuilder.Entity("KindergartenManagementSystem.Models.shared.Child", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("birth");

                    b.Property<string>("cla");

                    b.Property<string>("gua_name");

                    b.Property<string>("gua_phone");

                    b.Property<string>("home_addr");

                    b.Property<string>("name");

                    b.Property<bool>("sex");

                    b.HasKey("id");

                    b.ToTable("Children");
                });

            modelBuilder.Entity("KindergartenManagementSystem.Models.shared.Teacher", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("cla");

                    b.Property<string>("name");

                    b.HasKey("id");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("KindergartenManagementSystem.Models.shared.User", b =>
                {
                    b.Property<string>("user_name")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("auth");

                    b.Property<int>("banding");

                    b.Property<string>("password");

                    b.HasKey("user_name");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
