// <auto-generated />
using System;
using KindergartenManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KindergartenManagementSystem.Migrations
{
    [DbContext(typeof(EatScoreContext))]
    partial class EatScoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KindergartenManagementSystem.Models.EatScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Date");

                    b.Property<int?>("EatScoreId");

                    b.Property<string>("Note");

                    b.Property<int>("Score");

                    b.Property<int>("StuId");

                    b.Property<string>("Teacher");

                    b.HasKey("Id");

                    b.HasIndex("EatScoreId");

                    b.ToTable("EatScores");

                    b.HasData(
                        new { Id = 1, Date = "20210908", Note = "hhh", Score = 4, StuId = 1, Teacher = "fnsflm" },
                        new { Id = 2, Date = "20210901", Note = "eee", Score = 1, StuId = 2, Teacher = "fnsflm" },
                        new { Id = 3, Date = "20210902", Note = "eee", Score = 1, StuId = 2, Teacher = "fnsflm" },
                        new { Id = 4, Date = "20210903", Note = "eee", Score = 1, StuId = 2, Teacher = "fnsflm" },
                        new { Id = 5, Date = "20210904", Note = "eee", Score = 1, StuId = 2, Teacher = "fnsflm" },
                        new { Id = 6, Date = "20210905", Note = "eee", Score = 1, StuId = 2, Teacher = "fnsflm" }
                    );
                });

            modelBuilder.Entity("KindergartenManagementSystem.Models.EatScore", b =>
                {
                    b.HasOne("KindergartenManagementSystem.Models.EatScore")
                        .WithMany("EatScores")
                        .HasForeignKey("EatScoreId");
                });
#pragma warning restore 612, 618
        }
    }
}
